<a href="https://colab.research.google.com/github/PvrpleJade/Laboratory-7-Matrix-Operations/blob/main/58011_Lab7_SANTOS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ACTIVITY
## Task 1
Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$. In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import multi_dot
%matplotlib inline

# 1. $A \cdot B \neq B \cdot A$

In [ ]:
A = np.array([
    [1 ,3, 5],
    [2, -3, 6],
    [4, 6, -8]
])
B = np.array([
    [2 ,1, 3],
    [-5, 2, 7],
    [4, -1, -6]
])




In [ ]:
np.dot(A,B)

array([[  7,   2,  -6],
       [ 43, -10, -51],
       [-54,  24, 102]])

In [ ]:
np.dot(B,A)

array([[ 16,  21,  -8],
       [ 27,  21, -69],
       [-22, -21,  62]])

In [ ]:
np.array_equiv(A.dot(B),B.dot(A))

False

# 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$


In [ ]:
A = np.array([
    [1 ,3, 5],
    [2, -3, 6],
    [4, 6, -8]
])
B = np.array([
    [2 ,1, 3],
    [-5, 2, 7],
    [4, -1, -6]
])
C = np.array([
    [1 ,2, 3],
    [4, 5, 6],
    [7, 8, 9]
])





In [ ]:
np.dot(B,C)

array([[ 27,  33,  39],
       [ 52,  56,  60],
       [-42, -45, -48]])

In [ ]:
D = multi_dot([A,B,C])
D

array([[ -27,  -24,  -21],
       [-354, -372, -390],
       [ 756,  828,  900]])

In [ ]:
np.dot(A,B)

array([[  7,   2,  -6],
       [ 43, -10, -51],
       [-54,  24, 102]])

In [ ]:
E = multi_dot([A,B,C])
E

array([[ -27,  -24,  -21],
       [-354, -372, -390],
       [ 756,  828,  900]])

In [ ]:
np.array_equiv(D.dot(E),E.dot(D))

True

# 3. $A\cdot(B+C) = A\cdot B + A\cdot C$

In [ ]:
A = np.array([
    [1 ,3, 5],
    [2, -3, 6],
    [4, 6, -8]
])
B = np.array([
    [2 ,1, 3],
    [-5, 2, 7],
    [4, -1, -6]
])
C = np.array([
    [1 ,2, 3],
    [4, 5, 6],
    [7, 8, 9]
])





In [ ]:
A.dot(B+C)

array([[ 55,  59,  60],
       [ 75,  27,  -9],
       [-82,  -2,  78]])

In [ ]:
A.dot(B) + A.dot(C)

array([[ 55,  59,  60],
       [ 75,  27,  -9],
       [-82,  -2,  78]])

In [ ]:
np.array_equiv(A.dot(B+C),A.dot(B) + A.dot(C))

True

# 4. $(B+C)\cdot A = B\cdot A + C\cdot A$

In [ ]:
A = np.array([
    [1 ,3, 5],
    [2, -3, 6],
    [4, 6, -8]
])
B = np.array([
    [2 ,1, 3],
    [-5, 2, 7],
    [4, -1, -6]
])
C = np.array([
    [1 ,2, 3],
    [4, 5, 6],
    [7, 8, 9]
])





In [ ]:
D = B+C
D

array([[ 3,  3,  6],
       [-1,  7, 13],
       [11,  7,  3]])

In [ ]:
D.dot(A)

array([[ 33,  36, -15],
       [ 65,  54, -67],
       [ 37,  30,  73]])

In [ ]:
B.dot(A) + C.dot(A)

array([[ 33,  36, -15],
       [ 65,  54, -67],
       [ 37,  30,  73]])

In [ ]:
np.array_equiv(D.dot(A),B.dot(A) + C.dot(A))

True

# 5. $A\cdot I = A$

In [ ]:
I = np.array(A.dot(np.linalg.inv(A)), dtype =int)
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
A.dot(I)

array([[ 1,  3,  5],
       [ 2, -3,  6],
       [ 4,  6, -8]])

In [ ]:
np.array_equiv(A.dot(I),A)

True